version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: clinical_trials_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/app/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - .env

  # Prefect Server with Web UI
  prefect-server:
    build: .
    container_name: prefect_server
    ports:
      - "4200:4200"  # Prefect UI
    environment:
      - PREFECT_UI_URL=http://0.0.0.0:4200/api
      - PREFECT_API_URL=http://0.0.0.0:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_SERVER_API_PORT=4200
    command: prefect server start --host 0.0.0.0 --port 4200
    volumes:
      - prefect_data:/app/.prefect
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - .env

  prefect-worker:
    build: .
    container_name: prefect_worker
    depends_on:
      prefect-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - .:/app/workspace
    working_dir: /app/workspace
    command: >
      sh -c "
        sleep 10 &&
        prefect work-pool create --type process default-agent-pool || true &&
        prefect worker start --pool default-agent-pool
      "
    restart: unless-stopped
    env_file:
      - .env

  etl-runner:
    build: .
    container_name: clinical_trials_etl_runner
    depends_on:
      prefect-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - .:/app/workspace
    working_dir: /app/workspace
    profiles:
      - manual  # Only start when explicitly requested
    command: python prefect_flows.py --run-now
    env_file:
      - .env

  etl-scheduler:
    build: .
    container_name: etl_scheduler
    working_dir: /app/workspace
    command: >
      sh -c "
        sleep 15 &&
        python start_scheduled_etl.py
      "
    volumes:
      - .:/app/workspace
      - ./data:/app/data
    depends_on:
      prefect-server:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env

volumes:
  postgres_data:
  prefect_data: 
